            - name: DNSimple Create DNS Record
  # You may pin to the exact commit or the version.
  # uses: nicklinnell/dnsimple-create-record@a5cfee0d54d6e572e533de33c7468d753a85e1de
  uses: nicklinnell/dnsimple-create-record@v1
  with:
    # DNSimple access token
    token: 
    # Your DNSimple account number
    account: 
    # The zone name, e.g. example.com
    zone: 
    # The record name, without the domain. The domain will be automatically appended. Use an empty string to create a record for the apex.
    name: _discord.vologin.github.io
    # The type of DNS record to create, e.g. A, CNAME etc.
    type: TXT
    # The content of the DNS record e.g. IP address or domain name
    content: dh=ed6a7e0e27b3fa7e6651bbd71983658ba497b7af
    # Time to live for DNS record
    ttl: # optional
    # The priority level of the DNS record
    priority: # optional
    # Optional set of regions
    regions: # optional
          
